swagger: "2.3"
info:
    version: "1.0.0"
    title: Javascript-Server API
host: localhost:9000
basepath: /
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
paths: